variables:
  TF_ROOT: ${CI_PROJECT_DIR}/infra
  AUTHORIZED_KEY: ${AUTHORIZED_KEY}
  OPERATION:
    description: "Select CI/CD-operation"
    value: "terraform"
    options:
      - "terraform"
      - "ansible"
      - "k8s"
  
before_script:
  - cd ${TF_ROOT}
  - echo ${AUTHORIZED_KEY} | base64 -d > ./authorized_key.json

stages:
  - tests
  - plan
  - apply
  - terratest
  - ansible_deploy
  - destroy
  - build
  - package

plan:
  stage: plan
  script:
    - echo "Running Terraform plan..."
    - terraform init 
    - terraform plan
  rules:
    - if: $OPERATION == "terraform"
      when: always 

apply:
  stage: apply
  script:
    - echo "Applying Terraform..."
    - terraform init
    - terraform apply -auto-approve
  rules:
    - if: $OPERATION == "terraform"
      when: manual

destroy:
  stage: destroy
  script:
    - echo "Destroying Terraform infrastructure..."
    - terraform destroy -auto-approve
  rules:
    - if: $OPERATION == "terraform"
      when: manual

# Выполнение тестов checkov
#security_scan:

# Выполнение тестов terratest
#terratest:


# Деплой ansible-playbook
#ansible-deploy:

# Сборка и пуш Docker-образов в DockerHub
#build-and-push-images:

# Упаковка и пуш Helm-чарта в Nexus
#package-helm-chart:
