variables:
  TF_ROOT: ${CI_PROJECT_DIR}/infra
  AUTHORIZED_KEY: ${AUTHORIZED_KEY}
  OPERATION:
    description: "Select CI/CD-operation"
    value: "terraform"
    options:
      - "terraform"
      - "ansible"
      - "k8s"
  
before_script:
  - cd ${TF_ROOT}
  - echo ${AUTHORIZED_KEY} | base64 -d > ./authorized_key.json

# Пример stages для пайплайна
# stages:
#   - tests
  # - plan
#   - apply
#   - terratest
#   - ansible_deploy
#   - destroy
#   - build
#   - package
  
# Выполнение тестов checkov
#security_scan:


plan:
  stage: plan
  script:
    - echo "Running Terraform plan..."
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  rules:
    - if: '$OPERATION == "terraform"'
      when: always


# Создание инфраструктуры Terraform
#apply:


# Выполнение тестов terratest
#terratest:


# Деплой ansible-playbook
#ansible-deploy:


# Удаление инфраструктуры Terraform
#destroy:


# Сборка и пуш Docker-образов в DockerHub
#build-and-push-images:


# Упаковка и пуш Helm-чарта в Nexus
#package-helm-chart:
