---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongodb
  namespace: {{ .Release.Namespace }}
  labels: {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  serviceName: {{ .Release.Name }}-mongodb-service
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        resources: {{ toYaml .Values.mongodb.resources | nindent 12 }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-mongodb-config-map
        ports:
          - containerPort: {{ .Values.mongodb.containerPort }}
        volumeMounts:
          - name: mongodb-data
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.mongodb.storage.size }}
      storageClassName: {{ .Values.mongodb.storage.className }}
