---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-config-map
  namespace: {{ .Release.Namespace }}
  labels: {{- include "mongodb.labels" . | nindent 4 }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.env.dbRootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.env.dbRootPassword | quote }}
