---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.env.dbUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.env.dbPassword | b64enc }}