---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config-map
  namespace: {{ .Release.Namespace }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.dbName | quote }}
  POSTGRES_PORT: {{ .Values.postgres.containerPort | quote }}