---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-postgres-service
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      initContainers:
        - name: postgres-cleanup
          image: alpine:3.14
          command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/lost+found"]
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources: {{ toYaml .Values.postgres.resources | nindent 12 }}
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-postgres-secret
            - configMapRef:
                name: {{ .Release.Name }}-postgres-config-map
          resources: {{ toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
