---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
  namespace: {{ .Release.Namespace }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.postgres.containerPort }}
  selector:
    app: {{ .Release.Name }}-postgres
