---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          resources: {{ toYaml .Values.resources | nindent 12 }} 
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.containerPort }}
          volumeMounts:
          - name: {{ .Release.Name }}-{{ .Chart.Name }}-config-map
            mountPath: /etc/nginx/{{ .Values.nginxConf }}
            subPath: {{ .Values.nginxConf }}
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-config-map
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-config-map
            items:
              - key: {{ .Values.nginxConf }}
                path: {{ .Values.nginxConf }} 