---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config-map
  namespace: {{ .Release.Namespace }}
  labels: {{ include "backend-report.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.containerPort | quote }}

