---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{ include "backend-report.labels" . | nindent 4 }}
type: Opaque
data:
  DB: {{ .Values.env.dbUri | b64enc }}
