---
{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-vpa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    {{- include "backend.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        {{- toYaml .Values.vpa.resourceLimits | nindent 8 }}
        controlledResources: ["cpu", "memory"]
{{- end }}
