name: Sausage Store Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-backend:latest
            build-args: |
              VERSION=${{ github.sha }}

        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-frontend:latest

        - name: Push Backend-report to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend-report/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-backend-report:latest

  add_helm_chart_to_nexus:
      name: Add Helm Chart To Nexus
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub

      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Set up Helm
          uses: azure/setup-helm@v1
          with:
            version: '3.7.0'

        - name: Create Helm Chart
          run: |
            helm dependency update sausage-store-chart
            helm package sausage-store-chart

        - name: Upload Helm Chart to Nexus
          run: |
            helm plugin install https://github.com/chartmuseum/helm-push
            helm repo add nexus ${{ secrets.NEXUS_HELM_REPO }} \
              --username ${{ secrets.NEXUS_HELM_REPO_USER }} \
              --password ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
            helm cm-push sausage-store-*.tgz nexus \
              --context-path /repository/frostfree-sausage-store \
              --username ${{ secrets.NEXUS_HELM_REPO_USER }} \
              --password ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}

  deploy_helm_chart_to_kubernetes:
      name: Deploy Helm Chart To Kubernetes
      runs-on: ubuntu-latest
      needs: add_helm_chart_to_nexus

      steps:
        - name: Set up Helm
          uses: azure/setup-helm@v1
          with:
            version: '3.7.0'
            
        - name: Add Nexus Helm Repository
          run: |
            helm repo add nexus ${{ secrets.NEXUS_HELM_REPO }} \
              --username ${{ secrets.NEXUS_HELM_REPO_USER }} \
              --password ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
            helm repo update

        - name: Deploy Helm Chart to Kubernetes Cluster
          run: |
            mkdir -p ~/.kube
            echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
            chmod 600 ~/.kube/config
            helm upgrade \
              --install sausage-store nexus/sausage-store \
              --namespace ${{ secrets.SAUSAGE_STORE_NAMESPACE }} \
              --version 0.1.1
